version: "3"

services:

    rabbitmq-ecommerce:
        image: rabbitmq:3-management
        container_name: rabbit-ecommercestore
        environment:
            RABBITMQ_DEFAULT_USER: "notfound"
            RABBITMQ_DEFAULT_PASS: "notfound"              

    sql-server-ecommerce:
        image: notfound/ecommercestore-sql-server:latest
        container_name: ecommercestore-sql-server
        build:
            context: ../sql
            dockerfile: ./Dockerfile                
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"            

    api-catalogo:
        image: notfound/ecommercestore-api-catalogo:latest
        container_name: ecommercestore-api-catalogo
        build:
            context: ../src
            dockerfile: ./services/EcommerceStore.Catalogo.API/Dockerfile  
        restart: always         
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq-ecommerce
            - sql-server-ecommerce
    
    api-clientes:
        image: notfound/ecommerce-api-clientes:latest
        container_name: ecommercestore-api-clientes
        build:
            context: ../src
            dockerfile: ./services/EcommerceStore.Clientes.API/Dockerfile 
        restart: always       
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=https://+:5301;http://+5302
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq-ecommerce
            - sql-server-ecommerce
            - api-identidade

    api-identidade:
        image: notfound/ecommercestore-api-identidade:latest
        container_name: ecommercestore-api-identidade
        build:
            context: ../src
            dockerfile: ./services/EcommerceStore.Identidade.API/Dockerfile   
        restart: always     
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server-ecommerce        

    api-carrinho:
        image: notfound/ecommercestore-api-carrinho:latest
        container_name: ecommercestore-api-carrinho
        build: 
            context: ../src
            dockerfile: ./services/EcommerceStore.Carrinho.API/Dockerfile  
        restart: always      
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro            
        depends_on:
            - rabbitmq-ecommerce
            - sql-server-ecommerce
            - api-identidade
    
    api-pagamentos:
        image: notfound/ecommercestore-api-pagamentos
        container_name: ecommercestore-api-pagamentos
        build:
            context: ../src
            dockerfile: ./services/EcommerceStore.Pagamentos.API/Dockerfile   
        restart: always     
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=https://+:5701;http://+5702
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq-ecommerce
            - sql-server-ecommerce    
            - api-identidade
            - api-pedidos
    
    bff-compras:
        image: notfound/ecommercestore-bff-compras:latest
        container_name: ecommercestore-bff-compras
        build:
            context: ../src
            dockerfile: ./api gateways/EcommerceStore.Bff.Compras/Dockerfile        
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=https://+:5801;http://+5802
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:    
            - rabbitmq-ecommerce                 
            - api-identidade
            - api-carrinho                        
            - api-pagamentos   
            - api-pedidos        

    web-mvc:
        image: notfound/ecommercestore-web-mvc:latest
        container_name: ecommercestore-web-mvc
        build:
            context: ../src
            dockerfile: ./web/EcommerceStore.WebApp.MVC/Dockerfile    
        restart: always    
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=http://*:5001;
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on: 
            - api-catalogo
            - api-identidade
            - api-cliente
            - api-bff-compras

    api-pedidos:
        image: notfound/ecommercestore-api-pedidos:latest
        container_name: ecommercestore-api-pedidos
        build:
            context: ../src
            dockerfile: ./services/EcommerceStore.Pedidos.API/Dockerfile        
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=https://+:5601;http://+5602                        
            - ASPNETCORE_Kestrel__Certificates__Default__Password=melo880605
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ecommercestore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:         
            - rabbitmq-ecommerce
            - sql-server-ecommerce
            - api-identidade 
    
    ecommerce-server-nginx:
        image: notfound/ecommerce-server-nginx
        container_name: ecommerce-server-nginx
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc